import type { Metadata } from "next";
import "@/styles/globals.css";
import Toast from "@/components/common/Toast";
import ThemeProvider from "@/components/ThemeProvider";
import SWRProvider from "@/components/SWRProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider>
      <SWRProvider>
        <body>
          <Toast />
          {children}
        </body>
      </SWRProvider>
    </ThemeProvider>
  );
}
